title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
baseurl: ""
url: "https://therealrealok.github.io/"

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
